blogpost_index:
    path:     /
    defaults: { _controller: "TTplatformBundle:BlogPost:index" }
    methods:  GET

blogpost_show:
    path:     /{id}/show
    defaults: { _controller: "TTplatformBundle:BlogPost:show" }
    methods:  GET

blogpost_new:
    path:     /new
    defaults: { _controller: "TTplatformBundle:BlogPost:new" }
    methods:  [GET, POST]

blogpost_edit:
    path:     /{id}/edit
    defaults: { _controller: "TTplatformBundle:BlogPost:edit" }
    methods:  [GET, POST]

blogpost_delete:
    path:     /{id}/delete
    defaults: { _controller: "TTplatformBundle:BlogPost:delete" }
    methods:  DELETE
