blogcomment_index:
    path:     /
    defaults: { _controller: "TTplatformBundle:BlogComment:index" }
    methods:  GET

blogcomment_show:
    path:     /{id}/show
    defaults: { _controller: "TTplatformBundle:BlogComment:show" }
    methods:  GET

blogcomment_new:
    path:     /new
    defaults: { _controller: "TTplatformBundle:BlogComment:new" }
    methods:  [GET, POST]

blogcomment_edit:
    path:     /{id}/edit
    defaults: { _controller: "TTplatformBundle:BlogComment:edit" }
    methods:  [GET, POST]

blogcomment_delete:
    path:     /{id}/delete
    defaults: { _controller: "TTplatformBundle:BlogComment:delete" }
    methods:  DELETE
