adminChampionnat_index:
    path:     /
    defaults: { _controller: "TTplatformBundle:Championnat:index" }
    methods:  GET

adminChampionnat_show:
    path:     /{id}/show
    defaults: { _controller: "TTplatformBundle:Championnat:show" }
    methods:  GET

adminChampionnat_new:
    path:     /new
    defaults: { _controller: "TTplatformBundle:Championnat:new" }
    methods:  [GET, POST]

adminChampionnat_edit:
    path:     /{id}/edit
    defaults: { _controller: "TTplatformBundle:Championnat:edit" }
    methods:  [GET, POST]

adminChampionnat_delete:
    path:     /{id}/delete
    defaults: { _controller: "TTplatformBundle:Championnat:delete" }
    methods:  DELETE
