imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#parameters:
    #locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: [fr] }
    #translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  fr
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    auth_mode:  login
    encryption: ssl
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        jsqueeze:   ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            
fos_user:
    registration:
        form:
            type: Utilisateurs\UtilisateursBundle\Form\RegistrationType
    profile:
        form:
            type: Utilisateurs\UtilisateursBundle\Form\ProfileType
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Utilisateurs\UtilisateursBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        token_ttl: 10800
        email:
            #template:   email/password_resetting.email.twig
            template:   FOSUserBundle:Resetting:email.txt.twig
            
liip_imagine :
    # configure resolvers
    resolvers :
        # setup the default resolver
        default :
            # use the default web path
            web_path : ~
    # your filter sets are defined here
    filter_sets :
        # use the default cache configuration
        cache : ~
        # the name of the "filter set"
        sectionThumb :
            # adjust the image quality to 75%
            quality : 80
            # list of transformations to apply (the "filters")
            filters :
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [1807, 269], mode : outbound }
        raquetteLogo :
            quality : 80
            filters :
                thumbnail  : { size : [108, 149], mode : inset }
        multimediaThumbnail :
            quality : 80
            filters :
                thumbnail  : { size : [171, 171], mode : inset }
        avatar :
            quality : 80
            filters :
                thumbnail  : { size : [122, 122], mode : inset }
        sponsor :
            quality : 80
            filters :
                thumbnail  : { size : [253, 253], mode : inset }
        logoClub :
            quality : 100
            filters :
                thumbnail  : { size : [167, 78], mode : inset }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig    # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
hwi_oauth:
    connect:
        confirmation: true
        registration_form: fos_user.registration.form.factory
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookID
            google: googleID
    resource_owners:
        #Facebook Access
        facebook:
            type:                facebook
            client_id:           1251034744947844
            client_secret:       952a889e42923eb56cc0382363e3c5e9
            scope:               "email"
        #Google Access
        google:
            type:                google
            client_id:           583092207444-96eupudu7fie78l9h4pi4nmf12sa3oqj.apps.googleusercontent.com
            client_secret:       NaA_mVO2LkXM4d9IVMfXei__
            scope:               "https://www.googleapis.com/auth/plus.login"