<?php

namespace TT\platformBundle\Repository;

/**
 * anneCompetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anneCompetRepository extends \Doctrine\ORM\EntityRepository
{
}
