<?php

namespace TT\platformBundle\Repository;

/**
 * EquipeCompoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeCompoRepository extends \Doctrine\ORM\EntityRepository
{
}
