<?php

namespace TT\platformBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * matchCompetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matchCompetRepository extends \Doctrine\ORM\EntityRepository
{
    public function byDistinctEquipe()
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u.numeroEquie')
                ->distinct(true);

        
        return $qb->getQuery()->getResult();      
    }
}
