<?php

namespace TT\platformBundle\Repository;

/**
 * ResumPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumPostRepository extends \Doctrine\ORM\EntityRepository
{
}
